name = str(input('Digite seu nome completo: ')).strip().title()
print('Analisando nome... Aguarde')
nameList = name.split()
print('Primeiro nome: {}'.format(nameList[0]))
print('Último nome: {}'.format(nameList[len(nameList)-1]))
